# Generated by Django 4.2.5 on 2023-11-04 12:46

from django.db import migrations, models
import grf.models


class Migration(migrations.Migration):

    dependencies = [
        ('grf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='css_style',
            field=models.TextField(default=grf.models.get_report_styling_file_content),
        ),
    ]
